### ISSUE TITLE
gulp build throws some errors

### ISSUE THREAD

**Issue by harikt** [Postleaf/postleaf#6]
$ gulp build

```
events.js:154
      throw er; // Unhandled 'error' event
      ^
TypeError: this is not a typed array.
    at Function.from (native)
    at /home/hari/experiments/node/postleaf/node_modules/imagemin-svgo/index.js:25:19
    at optimizeOnceCallback (/home/hari/experiments/node/postleaf/node_modules/svgo/lib/svgo.js:44:17)
    at /home/hari/experiments/node/postleaf/node_modules/svgo/lib/svgo.js:65:9
    at Object.sax.onend (/home/hari/experiments/node/postleaf/node_modules/svgo/lib/svgo/svg2js.js:156:13)
    at emit (/home/hari/experiments/node/postleaf/node_modules/sax/lib/sax.js:640:35)
    at end (/home/hari/experiments/node/postleaf/node_modules/sax/lib/sax.js:683:5)
    at Object.write (/home/hari/experiments/node/postleaf/node_modules/sax/lib/sax.js:991:14)
    at Object.SAXParser.close (/home/hari/experiments/node/postleaf/node_modules/sax/lib/sax.js:157:38)
    at module.exports (/home/hari/experiments/node/postleaf/node_modules/svgo/lib/svgo/svg2js.js:169:28)
```

### Additional info

- Postleaf version: master
- Node version: v5.7.1
- Affected browsers:
- Operating system: Linux / Ubuntu 16.04

---

Note: This issue tracker is ONLY for bug reports and feature requests. If this is a personal support issue, please ask on the forum instead: community.postleaf.org

**Comment by harikt** [comment]
Oh I just understood it needs node version 7 :-)
